### ISSUE TITLE
Original select has 'required' attribute, doesn't work fine

### ISSUE THREAD

**Issue by fatshotty** [select2/select2#128]
Hello,

I think this is the better plugin I've ever used ;)

My question is related to the 'required' attribute.

let me explain better
I have a html page like this:

``` html
<form name="myForm" action="myAction" >
   <select id="myId" name="myName" required="true" >
       <option value="myvalue">An Element</option>
   </select>
   <button type="submit" >Go</button>
</form>
<script>
    $("#myId").select2({placeholder: "Select"});
</script>
```

When I click on the submit button of the form containing the select above, I see the internal browser's message "Please select an element from the list". That's right, because I want browser shows the message.

The problem is that the message is not correctly shown, maybe caused by "display: none" of the original select when I do:
$("#myId").select2()

Is there a way to avoid this annoyance?

thanks in advance and good job again ;)

**Comment by garak** [comment]
This is my solution:

```
.select2-container + select {
    position:absolute;
    display: block !important;
    visibility: hidden;
    height: 1px;
    margin-left: 10px;
    margin-top: -14px;
}
```

**Comment by kevin-brown** [comment]
Dropping this off of the 4.0 milestone as we are running out of time.

**Comment by Rvanlaak** [comment]
Adding the proven solution to the styling does not sound like a time consuming thing to me ;)

**Comment by kevin-brown** [comment]
Pull requests are always appreciated. We've had issues with hiding/shrinking the original element in the past.

**Comment by PikachuEXE** [comment]
@kevin-brown Please see #3069

**Comment by PikachuEXE** [comment]
I guess I will keep using my own solution and wait for 4.x to see if this issue is fixed

**Comment by Drachenfels** [comment]
Call me an idiot, but I have no clue how solution proposed by PikachuEXE could work for anyone. The problem is that select2 hides <select> tag and chrome check whether element is visible before popping up an validation error message. Because element is not visible Chrome complains.

I believe the only way to actually fix it and not work-around it is to remove 'required' attribute from element when select2 is initiated and add proper error handling as a part of select2.

Of one can be tempted to add element that are visible html-wise, yet human is not going to see it, but it will arms race. Till next version of browser detects such anomaly it will work, but do we really want to go this way? I doubt.

In case someone looks for a demo page that shows clearly a problem, go ahead and download this 'fiddle':

https://dl.dropboxusercontent.com/u/196245/test-select2-required-field/index.html

**Comment by kevin-brown** [comment]
I should mention that this is _better_ in 4.0.0 but _not fully fixed_. See https://github.com/select2/select2/issues/3824 for one of the more recent issues.

**Comment by Tin-Nguyen** [comment]
Hi @kevin-brown ,

I need to fix the issue. Do you know any work around to fix this manually?

**Comment by leventcandan** [comment]
I used Select2 Version: 3.4.2. with parsleyjs validations.
I use below with  but doesn't work:
 `<input type="hidden" id="name2" name="name2" style="width:100% !important" value="" required >`
Finaly. I use below. It is work.
`<input type="text" id="name2" name="name2" style="width:100% !important" value="" required >`

Note: I do not good my english

**Comment by bjegannathan-rpx** [comment]
Just so for people to understand this problem better with a fiddle!

This seems to have been fixed in version 3.5.4 in the sense an error message is shown. If you still want to reproduce the same problem in the version of select2 where this bug was prevalent. Here are the fiddles.

Problematic version : https://jsfiddle.net/jbragadeesh/55okbL58/
PikachuEXE's patch (overriden styles): https://jsfiddle.net/jbragadeesh/55okbL58/1/

**Comment by bragboy** [comment]
Just so for people to understand this problem better with a fiddle!

This seems to have been fixed in version 3.5.4 in the sense an error message is shown. If you still want to reproduce the same problem in the version of select2 where this bug was prevalent. Here are the fiddles.

Problematic version : https://jsfiddle.net/jbragadeesh/55okbL58/
PikachuEXE's patch (overriden styles): https://jsfiddle.net/jbragadeesh/55okbL58/1/

**Comment by vichu1988** [comment]
Was this overridden again in the version 4 bump? i sort a think this is again a problem?

**Comment by kevin-brown** [comment]
> Was this overridden again in the version 4 bump?

It's partially fixed in 4.0: https://github.com/select2/select2/issues/128#issuecomment-147446945

**Comment by ikki-lim** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8787549/17082412/ceba766c-51af-11e6-89a7-a7cac5fe5e7d.PNG)
Currently I'm using v4.0.3 and I have encounter this issue when using required.

**Comment by hackel** [comment]
This is still broken for me in Chrome 52.  My select2 field with the required attribute set gives: "An invalid form control with name='' is not focusable." and prevents the form from submitting.  I'm using select2 4.0.3.

**Comment by sameerr25** [comment]
Thanks @PikachuEXE 👍

**Comment by jeremysenn** [comment]
I'm also having the same issue as @hackel with select2 4.0.3

**Comment by jpic** [comment]
@jeremysenn does it work with the master branch ?

**Comment by jeremysenn** [comment]
I assume that's what I'm getting with this gem:
https://github.com/argerim/select2-rails

**Comment by jpic** [comment]
@jeremysenn I assume you'll revise your assumption after taking a look at the commit history of select2-rails, which plainly copies the source code from select2 release from Jun 14, 2016.

**Comment by jeremysenn** [comment]
Okay, my apologies. Thank you for pointing that out!

**Comment by epineda** [comment]
I'm also having the same issue informed by @ikki-lim with select2 v4.0.3

**Comment by epineda** [comment]
Finally I could solve it adding the following css:

```
.form-control.select2-hidden-accessible {
    top: 30px;
}
```

( I'm using select2 v4.0.3 with select2-bootstrap-theme v0.1.0-beta.9 )

:)

**Comment by apapacy** [comment]
Please, fix this truble. For validation reason only input type text mast be required.
But select required have some conflict with html5. 

`<input type="text" id="{{ id }}_autocomplete_input" value=""
        {%- if read_only is defined and read_only %} readonly="readonly"{% endif -%}
        {%- if disabled %} disabled="disabled"{% endif -%}
        {%- if required %} required="required"{% endif %}
    />

    <select id="{{ id }}_autocomplete_input_v4" data-sonata-select2="false"
        {%- if read_only is defined and read_only %} readonly="readonly"{% endif -%}
        {%- if disabled %} disabled="disabled"{% endif -%}
        {######  This is a fix jnly need %- if required %} required="required"{% endif %######}
    >
    </select>`

**Comment by hardyboyz** [comment]
in my case, I just inject the style like this :
```
.select2-hidden-accessible {
    top: 50px;
}
```
get the idea from @epineda 's code up there

**Comment by modestguy** [comment]
Thank you @epineda . Nice solution!

**Comment by sathyaprakash94** [comment]
We can enable the required HTML attribute functionality by adding the the required attribute to the input element of select2-focusser.

` $('#select2Element'').parent().children()[1].children(':eq(2)').prop('required', true);
`

**Comment by mac501** [comment]
Css hack solution that worked for me if someone still need it: 

`select.use-select-2.select2-attach-processed.required {
    display: block;
    position: absolute;
    height: 0px;
    pointer-events: none;
    border-color: transparent;
    background: transparent;
    appearance: none;
}`

**Comment by aniket-abmiro** [comment]
> Finally I could solve it adding the following css:
> 
> ```
> .form-control.select2-hidden-accessible {
>     top: 30px;
> }
> ```
> 
> ( I'm using select2 v4.0.3 with select2-bootstrap-theme v0.1.0-beta.9 )
> 
> :)

thanks

**Comment by Alex-Sichkar** [comment]
A simple JS solution that works well for me with Select2 v4.0.13 and v4.1.0-rc.0 in current versions of Chrome and Firefox, but has not been tested in other browsers.

```Javascript
document.addEventListener('invalid', function (event) {
  const element = event.target;

  if (element.classList.contains('select2-hidden-accessible')) {
    const select2Container = element.nextElementSibling;

    element.style.setProperty("height", `${select2Container.offsetHeight}px`, "important");
    element.style.setProperty("width", `${select2Container.offsetWidth}px`, "important");
  }
}, true); // Use capture phase because 'invalid' events do not bubble
```
