### ISSUE TITLE
Deleting selections from multi-select using backspace causes browser back in IE11

### ISSUE THREAD

**Issue by RochDs** [select2/select2#3168]
Deleting the tag using backspace causes browser back. This occurs in IE 11 but not in Chrome 41.0.

Jsfiddle: http://jsfiddle.net/6XvqX/822/

**Comment by kevin-brown** [comment]
I was able to reproduce the issue locally in IE, will do more testing later.

**Comment by RochDs** [comment]
Thank you Kevin!

**Comment by ithasyou** [comment]
Any news regarding this issue? It's really annoying

**Comment by ithasyou** [comment]
Still having the problem in IE9 and rc2

**Comment by ithasyou** [comment]
Solved modifying the following code:
this.$selection.on('keydown', '.select2-search--inline', function (evt) {
	evt.stopPropagation();
	self.trigger('keypress', evt);
	self._keyUpPrevented = evt.isDefaultPrevented();
	var key = evt.which;
	if (key === KEYS.BACKSPACE && self.$search.val() === '') {
		var $previousChoice = self.$searchContainer.prev('.select2-selection__choice');
		if ($previousChoice.length > 0) {
			var item = $previousChoice.data('data');
			self.searchRemoveChoice(item);
			self.$search.val("").blur().focus();
			evt.preventDefault();
		}
	}
});

**Comment by kevin-brown** [comment]
This is fixed on master but is not yet in a release.

**Comment by RochDs** [comment]
Hi Kevin, when will this fix be available in the release?

**Comment by kevin-brown** [comment]
This _should have_ been included in the 4.0.0 release that went out about two weeks ago. Can you confirm if you are still having issues with it?

**Comment by RochDs** [comment]
Hi Kevin, I have not yet taken the latest release. I will get it, and revert incase of issues.

**Comment by nfriend** [comment]
I am experiencing this issue in IE 11 when using `select2.js` or `select2.min.js`, but *not* when using `select2.full.js`.

As a side note, the fix in `select2.full.js` disables the backspace key completely after the deletion of a single tag, which is certainly better than navigating backwards in history, but still not as satisfactory as the expected behavior of continued tag deletion.

**Comment by kevin-brown** [comment]
> I am experiencing this issue in IE 11 when using select2.js or select2.min.js, but not when using select2.full.js.

Do you want to create a pair of jsfiddles (one with the full, one with the regular build) and a step by step set of instructions for how you are testing?

I'm not sure what would be included in the full builds that would be affecting this.

**Comment by nfriend** [comment]
I can't seem to reproduce the difference between `select2.js` and `select2.full.js` in a jsfiddle - perhaps I was just using an out-of-date version of library before.  I am still getting the backspace = back behavior using either version of the library in IE11, however:

- [jsfiddle using `select2.full.js`](http://jsfiddle.net/NathanFriend/a6tedrg3/)
- [jsfiddle using `select2.js`](http://jsfiddle.net/NathanFriend/rLmztr2d/)

Both jsfiddles use the latest version of library from the `/dist` directory on `master`.  To reproduce (in IE11):

- Select more than one option inside the Select2 control
- Try to delete all of the selected options using backspace

**Comment by thomashertog** [comment]
any updates on this issue?
I'm still experiencing this issue.
My setup is Select2-4.0.0  (doesn't matter whether I use the full or the normal script file)
Using IE 11

**Comment by licicego** [comment]
Using select2 with multiple tags in my project, the following code helped:
>   
      $(".select2-selection__rendered").on('keydown', function (e) {
            if ($(".select2-search__field valid").prevObject.context.activeElement.value == "" && e.which === 8) {
                event.preventDefault();
            }
        });

**Comment by MtarantoOa** [comment]
Hi guys Im using select2 in an Angular 2 template. We use the backspace key to delete the tags of the input. We found this solution:
`		
```
$.fn.select2.amd.require(['select2/selection/search'], function (Search) {
			var oldRemoveChoice = Search.prototype.searchRemoveChoice;

			Search.prototype.searchRemoveChoice = function () {
				oldRemoveChoice.apply(this, arguments);
				this.$search.val('');
			};
		});
```
`

That work great on Chrome. But on IE the second time I hit the backspace key the browser just go back.
I was looking for some solution like change the version of the library but it does not work for me.

Im using this version:  "select2": "4.0.3"

Do you know any workaround or how to fix this?

**Comment by alexweissman** [comment]
Have you tried pulling the `master` branch?

> This is fixed on master but is not yet in a release.

**Comment by MtarantoOa** [comment]
@alexweissman  Thanks for you answer.
Im using this library
https://github.com/NejcZdovc/ng2-select2

It uses select2 and I get the code of the library from npm. I think it get from master branch. 
I manually download and replace the files and still not working.

Thanks!

**Comment by alexweissman** [comment]
It looks like the wrapper pulls the last release (not `master`): https://github.com/NejcZdovc/ng2-select2/blob/master/package.json#L31 

Also, have you confirmed that this is still an issue even without using the wrapper?

**Comment by qw789** [comment]
It is still not working in IE11.......

**Comment by alexweissman** [comment]
It would seem that this is still a problem, even in `4.0.6-rc.1` with the fix from #4860.

**Comment by alexweissman** [comment]
#3394 claims to resolve this problem.

**Comment by pedrofurtado** [comment]
Discussion continues here -> https://github.com/select2/select2/pull/3394

**Comment by christopheroussy** [comment]
This is still broken with version 4.0.7 and `IE11` on windows 10.
