### ISSUE TITLE
Select2 v4 marking an option as selected does not refresh, instead duplicates element

### ISSUE THREAD

**Issue by sunalive** [select2/select2#3554]
I'm trying to mark an option as selected through another field value but the select2 control does not show the selection, instead duplicates the element with a disabled selected option (to the left).
The parent select is updated from another field in an iframe.  The option update works without select2 enabled.  I use the following code for the same.

```
$('.searchrow').click(function (e) {
    var srchdata = $(this).data('search').split("|");
    var target = ".srchtarget-" + $(this).data('target');
    var targetoption = target + " option[value='" + srchdata[0] + "']";
    var parentctrl = window.parent.document;
    $(targetoption,parentctrl).attr("selected","selected");
    $(target,parentctrl).select2();
});
```

This outputs the following:
<img width="342" alt="select2-update" src="https://cloud.githubusercontent.com/assets/2279283/8538263/161d76b8-2438-11e5-8f95-5ce4a1f95325.png">

Note that the option is also selected correctly in the select2 control.
Using `$(target,parentctrl).val(srchdata[0]).select2();` gives similar results too.
I tried to destroy the select2 before update, but that gives an error that 'destroy' option is applied in an element that is not using select2.

**Comment by kevin-brown** [comment]
Two things

1. Always trigger the `change` event after you change the value of an input on a page, it's what JS controls use to determine if there was a change. Browsers trigger it natively, you can trigger it in JS with `$('select').trigger('change')`.

2. You should use the `selected` property of the `<option>` instead of the attribute. This is what Select2 uses, and it's part of the native DOM specification for `HTMLOptionElement`. The main difference here is calling `.prop('selected', true)` instead of `attr('selected', 'selected')`.

If your issue isn't fixed after making these changes, can you wrap this up into a small test case (hosted on jsbin or jsfiddle) where we can reproduce the issue?

**Comment by sunalive** [comment]
I tried both options but the result was the same.  Here's the jsbin for the code (without iframe, but that should not make any difference).  The code works here but I don't think the select2 loads.  It seems to show the native control (which worked in my case too).  You could alter this with correct path for select2.

http://jsbin.com/sofodidijo/edit?html,css,js,output

**Comment by kevin-brown** [comment]
It looks like jsDelivr is giving the wrong JS/CSS links (cdnjs is giving the right ones), I've corrected those in the following jsbins.

http://jsbin.com/voqowufaca/1/edit?html,css,js,output
http://jsbin.com/fakidenotu/1/edit?html,css,js,output

After fixing the JS and CSS, it appears to work with Select2.

**Comment by sunalive** [comment]
Is this version in cdn different than what is available for download?  Because, I use a downloaded copy in my project but I linked the jsDelivr in jsbin just to show you what's happening.  I still have that bug with my copy which says v4.0.0

**Comment by kevin-brown** [comment]
If you're using a downloaded version, make sure to pull it from the tag (4.0.0) which is a stable version instead of the master branch, which is unstable.

https://github.com/select2/select2/tree/4.0.0

**Comment by sunalive** [comment]
I downloaded the latest release version from the site at https://github.com/select2/select2/archive/4.0.0.zip with the tag *kevin-brown released this on Apr 26 · 136 commits to master since this release*.  Isn't that the stable one?  However, I downloaded the stable version that you have indicated but the result is still the same.  

I sort of put a jsbin with iframe that loads jsfiddle which contains the button that doesn't work. I guess the iframe control is not able to access the parent. 

http://jsbin.com/vexupu/edit?html,js,output

**Comment by sunalive** [comment]
This has been open for a long time.  Any idea when is this likely to be fixed?

**Comment by kevin-brown** [comment]
> Any idea when is this likely to be fixed?

Right now this isn't on any of the lists of tickets we are going to close before we release 4.0.1, so I have no idea when this will be fixed.

The process can be sped up if the root cause is tracked down, even more so if a pull request is created that fixes the issue.

**Comment by sunalive** [comment]
I found the solution after long last.  The issue was with the way the parent DOM was being accessed.  I changed the following two lines:

    var parentctrl = window.parent.document;
    $(targetoption,parentctrl).attr("selected","selected");

to

    var parentctrl = window.parent;     
    parentctrl.$(targetoption).prop("selected", true).parent().select2();

and it works.  The same works with `val()` property too.

    parentctrl.$(targetoption).val("IN").parent().select2();

However, with multiselect, the `val()` replaces the already selected option if the iframe window is accessed again for adding another (unless I also pass the previous selected value again as an array).  `prop()` works well in this case.

**Comment by dehy** [comment]
I have a similar problem.

I have a select2 field with ajax query, and a pre-selected option. The ajax query is displayed correctly but when I select an entry, it appends the entry to the list of options and do not update the "selected" property, keeping it on the previous (and original) option.

**Comment by metamaker** [comment]
Same here.

**Comment by MohsenAfshari** [comment]
hi dehy 
how to resove your problem . i dont

**Comment by alexweissman** [comment]
@sunalive are you still experiencing this problem?  Have you seen issue #4608?  Your example link is no longer accessible, but if it's a problem with iframes then it could be the same issue.

**Comment by brianmcgee** [comment]
I am experiencing the exact same behaviour as @dehy.

**Comment by sunalive** [comment]
@Alexweissman: No. I no longer have this issue. I had solved this long ago and have given the solution in the comment above @dehy.

@Others: If the option is preselected while loading the page, you'll have to deselect it with `$(elem).attr()` while you receive the Ajax response.  This is because the selected attribute is part of the page html and not js dom.  If the option is being selected in the dom (by the user after loading the page), you can manipulate it with `.prop()`.  Please see my solution for an example.

**Comment by alexweissman** [comment]
Ah, ok.  Isn't `prop` generally [preferred when setting dynamic attributes](http://api.jquery.com/prop/) anyway?

**Comment by sunalive** [comment]
Yes. You'll use `.prop()` for manipulating the dom (dynamically) but it is not effective for manipulating page html attributes directly. The reason is that manipulated dynamic attributes are not available for other objects outside the object that is manipulating it until they are saved (which is expected) but the page html is universal as it is already loaded and available for all.

**Comment by HalShaw** [comment]
Same as dehy, the view didn't update while the value changed.

**Comment by zedsh** [comment]
My solution:  
$('select.select2-ajax').each(function() {
        $(this).select2({
            width: '100%',
            ajax: {
                url: $(this).data('get-items-route'),
                data: function (params) {
                    var query = {
                        search: params.term,
                        type: $(this).data('get-items-field'),
                        page: params.page || 1
                    }
                    return query;
                }
            }
        });

        $(this).on('select2:select',function(e){
            var data = e.params.data;
            $(e.currentTarget).find("option[value='" + data.id + "']").attr('selected','selected');
        });

        $(this).on('select2:unselect',function(e){
            var data = e.params.data;
            $(e.currentTarget).find("option[value='" + data.id + "']").attr('selected',false);
        });
    });
