### ISSUE TITLE
ensureHighlightVisible not triggered on first time open

### ISSUE THREAD

**Issue by zellerda** [select2/select2#3956]
Hi the ensureHighlightVisible function is not tiggered when the dropdown is visible for the first time, so if the selected element is not visible the dropdown doesn't scroll to the element.

**Comment by zellerda** [comment]
I have corrected like this:
```javascript
container.on('results:all', function(params){
    self.clear();
    self.append(params.data);
    if(container.isOpen()){
        self.setClasses();
        // Add the line below
        self.ensureHighlightVisible();
    }
});
```

**Comment by Sciscitator** [comment]
@zellerda: Where did you add this?

I'm also experiencing the same bug with 4.0.1. This is why I had to go back to 4.0.

**Comment by urkle** [comment]
ensureHighlghtVisible actually is being called on the first open.. However the getHighlightedResults method is not returning any results the first time it's called. (it's being called too early)

And this still occurs in 4.0.2

**Comment by kevin-brown** [comment]
This ended up being fixed by https://github.com/select2/select2/pull/4238.
