### ISSUE TITLE
AJAX data source "the results could not be loaded" error

### ISSUE THREAD

**Issue by MichaelMackus** [select2/select2#4355]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Navigate to: https://select2.github.io/examples.html#data-ajax
2. Input text
3. Before the ajax results are loaded, input more text
## Expected behavior and actual behavior

When I follow those steps, I see...

"The results could not be loaded." is displayed (then, after a while, the results are populated)

I was expecting...

"Searching.." displayed as more text is inputted
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries
- jQuery version: v1.11.2
- Select2 version: master (v4.0.2#master)
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by arirangz** [comment]
+1

**Comment by stephpy** [comment]
Tested on macos x, same issue. fixed by https://github.com/select2/select2/pull/4356.

**Comment by rajdeep26** [comment]
What's the temporary solution till this bug is fixed?

**Comment by vladkazantsev** [comment]
A workable cover up for people that cant edit the source code due to loaded by bower / dependencies etc, but just want to hide the ugly message:

`...).select2({
   language: {
            errorLoading:function(){
                return "Searching..."
            }
   },`

**Comment by JefMari** [comment]
@vladkazantsev approach is enough for me :)

**Comment by bpromasmb** [comment]
@vladkazantsev doesn't work if you've already set an alternate language. Also it doesn't display the message correctly if there is an *actual* error to the search.

If you're loading an alternate language file you could go into the file and change the errorLoading text, which would then affect every Select2 in your application, or you could generate a new language file with the changed errorLoading text to use just on the selects that have ajax search.

**Comment by bpromasmb** [comment]
One solution is to roll back to v.4.0.1 which does not have this issue as far as I can tell.

**Comment by Braunson** [comment]
@vladkazantsev approach works **IF** you don't have an alt language set, additionally if you DO have an error, it just sits there showing 'Searching...'.

Ideally until this is resolved @bpromasmb's suggestion of downgrading to 4.0.1 resolves this.

**Comment by raratiru** [comment]
+1

**Comment by alexweissman** [comment]
Please refrain from "+1" comments.  Simply click 👍 to show your interest in an issue.

**Comment by KuenzelIT** [comment]
I have the same problem. Is there a solution now? Can it be merged? Thank you!

**Comment by alexweissman** [comment]
Have you updated to [4.0.6-rc.0](https://github.com/select2/select2/releases/tag/4.0.6-rc.0)?  It should be fixed since #4356 was merged.

**Comment by KuenzelIT** [comment]
Hey,
I took version 4.0.4 as it is linked one the official installation page:
https://select2.org/getting-started/installation

I'll try the new version, thanks for the hint!

**Comment by alexweissman** [comment]
Ah ok, I will update the docs.

**Comment by iFlash** [comment]
Just tried it. This 4.0.6 rc does not solve this issue. Still get the error message during typing.
