### ISSUE TITLE
Loses focus on close.

### ISSUE THREAD

**Issue by ajcastro** [select2/select2#4971]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go https://select2.github.io/examples.html. 
2. Try to navigate a select2 element by using tab. 
3. Then select an option. After closed, the focus is gone. 

## Expected behavior and actual behavior

When I follow those steps, I see... that the focus is not on the current select2 element. 

I was expecting... the focus should still be on the select2 element, and then when I press tab, it should go to the next select2 element. The latest version is not keyboard friendly. I would love the keyboard behaviour in [v3.5.3](http://select2.github.io/select2/).

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ptheofan** [comment]
Same issue. Using tab, arriving on select2 elem. Hit enter, it opens, I select the entry - focus is lost. Results, next tab go top of page according to tab-indexes

**Comment by shoe788** [comment]
Same issue. This seems to work as a workaround edit to select2.js

    this.on('close', function () {
        self.$container.removeClass('select2-container--open');

        //FIX for focus on close
        self.$selection.focus();
    });

**Comment by oh-ren** [comment]
Workaround in userland (not thoroughly tested):
```js
$('select').select2().on('select2:close', function(e) {
    let $select2 = $(this).data('select2');
    $select2.$selection.focus();
});
```

**Comment by alexweissman** [comment]
Is this related to the problem addressed in #4860?

**Comment by oh-ren** [comment]
It seems so. I'm only just looking into Select2, so not really familiar with the code base.
I added the base.js timeout hack to the dist file, seems to fix this focus issue in FF56. Not sure what the effect is of the change in search.js

**Comment by alexweissman** [comment]
Hmm.  Seems like creating a Github Project might be a good way to aggregate these related issues for now.

**Comment by alexweissman** [comment]
Ok, created this project: https://github.com/select2/select2/projects/2

**Comment by alexweissman** [comment]
There's also the issue reported in #4419, fixed by #4427.  Is this the same issue?

**Comment by jpic** [comment]
@alexweissman this seems like a different issue: after selecting an issue with the keyboard -> the focus is *lost* -> pressing tab again starts over from the beginning of the page -> you have to go over the sidebar links to get back at the autocomplete.

**Comment by alexweissman** [comment]
No, @jpic I am fairly sure that this is the same issue.  After merging in @nino-s 's fix (#4427) and releasing 4.0.4, you can see that this problem no longer occurs on the demo page: https://select2.org/getting-started/basic-usage

**Comment by PieterjanDeClippel** [comment]
Apparently the issue is back. See [demo-page](https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox).
Can this problem be fixed once again?

**Comment by Dannymx** [comment]
This issue is still present in latest 4.0.6 and 4.0.7 rc.0

For me when I click one select and then click another select, the focus stays with the previous select.
